BEGIN TRANSACTION;

-- configuration

INSERT INTO CONFIGURATION VALUES
    ('TIMER-PRECISION', 'CENTISECONDS');

-- version

UPDATE CONFIGURATION SET VALUE = '0.7' WHERE KEY = 'VERSION';

COMMIT;