BEGIN TRANSACTION;

UPDATE CONFIGURATION SET VALUE = '0.10.0' WHERE KEY = 'VERSION';

INSERT INTO CONFIGURATION VALUES
    ('HIDETIMER-ENABLED', 'FALSE');

INSERT INTO CONFIGURATION VALUES
    ('DAILYSESSION-ENABLED', 'FALSE');

COMMIT;